services:
  nginx-ui:
    container_name: nginx-ui
    image: uozi/nginx-ui:latest
    restart: always
    stdin_open: true
    tty: true
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - '/opt/docker/nginx-ui/nginx:/etc/nginx'
      - '/opt/docker/nginx-ui/ui:/etc/nginx-ui'
      - '/opt/docker/nginx-ui/logs:/var/log/nginx'
      - '/opt/docker/nginx-ui/www:/var/www'
      - '/var/run/docker.sock:/var/run/docker.sock'
    ports:
      - '12800:80'
      - '12443:443'
    network_mode: bridge

networks:
  bridge:
    external: true
